#!/bin/sh

# `gshuf` shuffles rows in a file
# `gshuf (shuf)` is in `coreutils` which can be downloaded by homebrew.
# `g` is prefixed to commands in coreutils. original command name is `shuf`.
# `sort -R` sounds too slow. see http://stackoverflow.com/questions/886237/how-can-i-randomize-the-lines-in-a-file-using-standard-tools-on-red-hat-linux

readonly src=$HOME/bin/resources/jptdiff.dat

while getopts :hn: OPT
do
    case ${OPT} in
        "n" )
            n=${OPTARG}
            ;;
        "h" )
            h=1
            ;;
        * )
            echo "Usage: $(basename ${0}) [-n NUMBER] [-h]" 1>&2
            exit 1
            ;;
    esac
done

gshuf -n ${n:=10} ${src} | while read diffpt drawpt hand
do
    read -s -r -p "${diffpt}" input < /dev/tty
    if [ -z ${input} ]; then
        echo "->${drawpt}(${hand})"
        continue
    fi
    if [ ${h} ]; then
        if [ ${input} != ${hand} ]; then
            echo "->${hand}"
        fi
    else
        if [ ${input} != ${drawpt} ]; then
            echo "->${drawpt}"
        fi
    fi
done
