#!/bin/sh

# `gshuf` shuffles rows in a file
# `gshuf (shuf)` is in `coreutils` which can be downloaded by homebrew.
# `g` is prefixed to commands in coreutils. original command name is `shuf`.
# `sort -R` sounds too slow. see http://stackoverflow.com/questions/886237/how-can-i-randomize-the-lines-in-a-file-using-standard-tools-on-red-hat-linux

readonly datasource=$HOME/bin/datasource/jptdiff.dat

while getopts :hn:rs OPT
do
    case ${OPT} in
        "h" )
            h=1
            ;;
        "n" )
            n=${OPTARG}
            ;;
        "r" )
            r=1
            ;;
        "s" )
            s=1
            ;;
        * )
            echo "Usage: $(basename ${0}) [-h] [-n NUMBER] [-r] [-s]" 1>&2
            exit 1
            ;;
    esac
done

gshuf -n ${n:=10} ${datasource} | while read cdiffpt pdiffpt drawpt hand
do
    rnd=`gshuf -i 0-1 -n 1`
    # child
    if [ ${rnd} -eq 0 ]; then
        read -s -r -p "${cdiffpt}_" input < /dev/tty
        if [ -z ${input} ]; then
            echo "->${drawpt}(${hand})"
            continue
        fi
        if [ ${h} ]; then
            if [ ${input} != ${hand} ]; then
                echo "->${hand}"
            fi
        else
            if [ ${input} != ${drawpt} ]; then
                echo "->${drawpt}"
            fi
        fi
    # parent
    else
        read -s -r -p "${pdiffpt}^" input < /dev/tty
        if [ -z ${input} ]; then
            echo "->${drawpt}(${hand})"
            continue
        fi
        if [ ${h} ]; then
            if [ ${input} != ${hand} ]; then
                echo "->${hand}"
            fi
        else
            if [ ${input} != ${drawpt} ]; then
                echo "->${drawpt}"
            fi
        fi
    fi
done
