#!/bin/sh

# `gshuf (shuf)` is in `coreutils` which can be downloaded by homebrew.
# `g` is prefixed to commands in coreutils. original command name is `shuf`.

pt=25000
minhit=1000
maxhit=5000

players=($pt $pt $pt $pt)
winds=("T" "N" "S" "P")

for i in `seq 1 10`
do
    hit=$(( `gshuf -i $minhit-$maxhit -n 1` / 100 * 100 ))

    for j in `gshuf -i 0-3 -n 2`
    do
        players[$j]=$(( ${players[$j]} + $hit ))
        hit=$(( $hit * -1 ))
    done
done

you=`gshuf -i 0-3 -n 1`
i=0
for player in "${players[@]}"
do
    [ $you -eq $i ] && pointer="*" || pointer=" "
    echo "${pointer}${winds[${i}]}: ${player}"
    let i++
done
