#!/bin/sh

# `gshuf` shuffles rows in a file
# `gshuf (shuf)` is in `coreutils` which can be downloaded by homebrew.
# `g` is prefixed to commands in coreutils.
# `sort -R` sounds too slow. ref http://stackoverflow.com/questions/886237/how-can-i-randomize-the-lines-in-a-file-using-standard-tools-on-red-hat-linux

SRC=$HOME/bin/src
gshuf -n 10 ${SRC}/jten.dat | while read a b c
do
  #echo ${a} ${b} ${c}
  read -s -r -p "${a}/" ans < /dev/tty
  if [ ${ans} != ${b} ]; then
      echo "->${b}"
  fi
done
